version: 2
updates:

    -   package-ecosystem: "composer"
        directory: "/"
        schedule:
            interval: "weekly"
        target-branch: "internal"
        open-pull-requests-limit: 0
        labels:
            - "dependencies"
